# Generated by Django 4.1 on 2023-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_alter_cancha_table_alter_roles_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='lat',
            field=models.FloatField(blank=True, db_column='lat', null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='lng',
            field=models.FloatField(blank=True, db_column='lng', null=True),
        ),
    ]
